# Copyright (c) 2018-2025, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="pynvjitlink/VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data["project"] %}
{% set project_urls = project_data["urls"] %}

package:
  name: pynvjitlink
  version: {{ version }}

source:
  path: ../../..

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=pynvjitlink-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=pynvjitlink-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
    - libnvjitlink-dev

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    - cmake >=3.26.4,!=3.30.0
    - ninja
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libnvjitlink-dev
    - libnvjitlink-static
    - python
    - pip
    - rapids-build-backend >=0.3.0,<0.4.0dev0
    - scikit-build-core >=0.10.0
  run:
    - python
    - numba >=0.58
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x.x') }}

about:
  home: {{ project_urls["Homepage"] }}
  dev_url: {{ project_urls["Repository"] }}
  doc_url: {{ project_urls["Documentation"] }}
  license: {{ project_data["license"] }}
  license_family: Apache
  license_file: LICENSE
  license_url: {{ project_urls["License"] }}
  summary: nvJitLink Python binding
